# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.0.1' # Exact version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint==2.6.0 pytest==5.2.4 pandas==1.1.4
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: pylint
      run: |
        pylint src tests
    - name: pytest
      run: |
        pytest tests
